# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lfabbian <marvin@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/22 13:19:59 by lfabbian          #+#    #+#              #
#    Updated: 2022/09/22 13:55:43 by lfabbian         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
CFLAGS = -WAll -Wextra -Werror

all:
	//ecrire qqch

clean:
	//ecrire qqch

fclean: clean

re: fclean all
